// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.Comments.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_id");

                    b.Property<int>("Dislikes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("dislikes");

                    b.Property<int>("Likes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("likes");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by_id");

                    b.Property<Guid>("author_id")
                        .HasColumnType("uuid(36)");

                    b.Property<Guid>("model_id")
                        .HasColumnType("uuid(36)");

                    b.HasKey("Id");

                    b.HasIndex("author_id");

                    b.HasIndex("model_id");

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("Core.Models.Filaments.Filament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("color");

                    b.Property<string>("Diameter")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("diameter");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("manufacturer");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("filaments", (string)null);
                });

            modelBuilder.Entity("Core.Models.Files.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("extension");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("path");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by_id");

                    b.Property<Guid?>("model_id")
                        .HasColumnType("uuid(36)");

                    b.HasKey("Id");

                    b.HasIndex("model_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("Core.Models.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AIGenerated")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ai_generated");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid(36)");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("categories");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("deleted_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IsRemix")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("is_remix");

                    b.Property<int?>("License")
                        .HasColumnType("int")
                        .HasColumnName("license");

                    b.Property<bool>("NSFW")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("nsfw");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("Privacy")
                        .HasColumnType("int")
                        .HasColumnName("privacy");

                    b.Property<DateTime?>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("char(36)")
                        .HasColumnName("updated_by_id");

                    b.Property<bool>("WIP")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("wip");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("models", (string)null);
                });

            modelBuilder.Entity("Core.Models.Models.PrintSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("InfillPercentage")
                        .HasColumnType("int")
                        .HasColumnName("infill_percentage");

                    b.Property<decimal>("LayerHeight")
                        .HasColumnType("decimal(5,3)")
                        .HasColumnName("layer_height");

                    b.Property<bool>("Supports")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("supports");

                    b.Property<int>("WallLoops")
                        .HasColumnType("int")
                        .HasColumnName("wall_loops");

                    b.HasKey("Id");

                    b.ToTable("print_settings", (string)null);
                });

            modelBuilder.Entity("Core.Models.Printers.Printer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BuildVolumeX")
                        .HasColumnType("int")
                        .HasColumnName("build_volume_x");

                    b.Property<int>("BuildVolumeY")
                        .HasColumnType("int")
                        .HasColumnName("build_volume_y");

                    b.Property<int>("BuildVolumeZ")
                        .HasColumnType("int")
                        .HasColumnName("build_volume_z");

                    b.Property<string>("Connectivity")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("connectivity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("DefaultNozzleDiameter")
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("default_nozzle_diameter");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExtruderCount")
                        .HasColumnType("int")
                        .HasColumnName("extruder_count");

                    b.Property<string>("ExtruderType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("extruder_type");

                    b.Property<bool>("HasAutoLeveling")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_auto_leveling");

                    b.Property<bool>("HasEnclosure")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_enclosure");

                    b.Property<bool>("HasFilamentSensor")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_filament_sensor");

                    b.Property<bool>("HasHeatedBed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_heated_bed");

                    b.Property<bool>("HasHeatedChamber")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_heated_chamber");

                    b.Property<bool>("HasPowerLossContinue")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_power_loss_continue");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("manufacturer");

                    b.Property<int>("MaxBedTemp")
                        .HasColumnType("int")
                        .HasColumnName("max_bed_temp");

                    b.Property<int>("MaxNozzleTemp")
                        .HasColumnType("int")
                        .HasColumnName("max_nozzle_temp");

                    b.Property<decimal>("MaxPrintSpeed")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("max_print_speed");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("model");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_usd");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int")
                        .HasColumnName("release_year");

                    b.Property<string>("SupportedMaterials")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("supported_materials");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.ToTable("printers", (string)null);
                });

            modelBuilder.Entity("Core.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("salt");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedById")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Core.Models.Users.UserLogin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ip_address");

                    b.Property<bool?>("Successful")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Core.Models.Comments.Comment", b =>
                {
                    b.HasOne("Core.Models.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("author_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("model_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Core.Models.Files.File", b =>
                {
                    b.HasOne("Core.Models.Models.Model", null)
                        .WithMany("Files")
                        .HasForeignKey("model_id");
                });

            modelBuilder.Entity("Core.Models.Models.Model", b =>
                {
                    b.HasOne("Core.Models.Users.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Core.Models.Models.Model", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
