services:
  api:
    build:
      target: build
    volumes:
      - ./backend:/app/backend
      - ./PolyBucket.sln:/app/PolyBucket.sln
    command: dotnet watch run --urls http://*:11666
    healthcheck:
      disable: true

  client:
    ports:
      - "32768:3000"
    build:
      target: development
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    command: npm start
    environment:
      - VITE_API_URL=http://localhost:11666 