// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolyBucket.Api.Data;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PolyBucketDbContext))]
    [Migration("20251023041940_FixCanLoginForExistingUsers")]
    partial class FixCanLoginForExistingUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This is a data-only migration, no model changes
#pragma warning restore 612, 618
        }
    }
}

